name: highlite_flutter_mvp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  socket_io_client: ^2.0.3+1
  http: ^0.13.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  connectivity_plus: ^5.0.2
  flutter_svg: ^2.0.9
  get_it: ^7.6.7
  injectable: ^2.3.2
  package_info_plus: ^8.0.2
  flutter_staggered_grid_view: ^0.7.0
  photo_view: ^0.14.0
  mask_text_input_formatter: ^2.7.0
  flutter_keyboard_visibility: ^5.4.1
  emoji_picker_flutter: ^1.6.3
  currency_text_input_formatter: ^2.1.11
  easy_rich_text: ^2.1.0
  flutter_bloc: ^8.1.3
  get: ^4.6.6
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_sign_in: ^6.2.1
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  flutter_facebook_auth: ^5.0.11
  json_annotation: ^4.8.1
  form_validator: ^2.1.1
  video_player: ^2.8.2
  dotted_border: ^2.1.0
  sizer: ^2.0.15
  cloud_firestore: ^5.2.1
  dio: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  loading_animation_widget: ^1.2.1
  avatar_glow: 2.0.2
  flutter_slidable: ^3.1.0
  share_plus: ^7.2.2
  envied: ^0.5.4+1
  envied_generator: ^0.5.4+1
  custom_sliding_segmented_control: ^1.8.1
  firebase_messaging: ^15.0.4
  video_thumbnail: ^0.5.3
  cached_network_image: ^3.1.0
  flutter_multi_formatter: ^2.12.8
  pay: ^2.0.0
  app_settings: ^5.1.1
  uuid: ^4.4.0
  firebase_storage: ^12.1.3
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  flutter_inappwebview: ^6.0.0
  video_compress: ^3.1.2

#  firebase_auth_oauth: ^1.2.2
dependency_overrides:
  archive: ^3.6.1
  win32: ^5.5.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.3
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/env/
    - assets/fixtures/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
