// File generated by FlutterFire CLI.


// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1ahY_T9p7euAbem48kx2Z2TYDSqeefhc',
    appId: '1:179566512780:web:eb0565ec7573e509c849a9',
    messagingSenderId: '179566512780',
    projectId: 'highlite-app',
    authDomain: 'highlite-app.firebaseapp.com',
    storageBucket: 'highlite-app.appspot.com',
    measurementId: 'G-516HVKW26H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjiIQcMRlUWlnzYhfz8IPPreGoa1cAZXg',
    appId: '1:179566512780:android:30b9544aecdc162bc849a9',
    messagingSenderId: '179566512780',
    projectId: 'highlite-app',
    storageBucket: 'highlite-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUh0ly0Hw1WHjcLBvK-vx96jr9tucGzcM',
    appId: '1:179566512780:ios:749c5dd1470aa990c849a9',
    messagingSenderId: '179566512780',
    projectId: 'highlite-app',
    storageBucket: 'highlite-app.appspot.com',
    iosClientId: '179566512780-4r5o5p32a6b2u8urnb6fpob9noe3b2vv.apps.googleusercontent.com',
    iosBundleId: 'com.example.highliteFlutterMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUh0ly0Hw1WHjcLBvK-vx96jr9tucGzcM',
    appId: '1:179566512780:ios:273d521f4e3fc0b9c849a9',
    messagingSenderId: '179566512780',
    projectId: 'highlite-app',
    storageBucket: 'highlite-app.appspot.com',
    iosClientId: '179566512780-n4qlm92rjhs6ltqajotf5vgld8juc4i8.apps.googleusercontent.com',
    iosBundleId: 'com.example.highliteFlutterMvp.RunnerTests',
  );
}
